# Artifical Neural Network

### This model will predict whether the customer  will leave  from the bank or not!!!

### Importing Libraries

In [1]:
import pandas as pd 
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

In [5]:
# Importing the dataset
data=pd.read_csv("Churn_Modelling.csv",index_col=False)

In [6]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
# Splitting into idependent and dependent variables
X=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values

In [8]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [9]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding Catagories dataset using label encoder

In [12]:
from  sklearn.preprocessing import LabelEncoder

In [13]:
# Using label encoder transform Gender Collumn
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [14]:
print(X[:,2])

[0 0 0 ... 0 1 0]


### One Hot Coding for Geography Column

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [16]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into training and testing

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.30,random_state=42)

In [24]:
X_train.shape , X_test.shape

((7000, 12), (3000, 12))

In [25]:
y_train.shape , y_test.shape

((7000,), (3000,))

### Feature Scaling

In [26]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

### Building ANN model

In [27]:
#Initializing the ANN
ann=tf.keras.models.Sequential()

In [28]:
## Adding first hidden layer  and input layer 
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [29]:
## Adding second hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [30]:
## Adding third hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [31]:
##Aing output layer
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

### Training the ANN

In [32]:
## Compiling the ANN
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [33]:
# Training the Ann
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
219/219 [==============================] - 2s 955us/step - loss: 0.6687 - accuracy: 0.6509
Epoch 2/100
219/219 [==============================] - 0s 861us/step - loss: 0.4748 - accuracy: 0.7958
Epoch 3/100
219/219 [==============================] - 0s 870us/step - loss: 0.4557 - accuracy: 0.7962
Epoch 4/100
219/219 [==============================] - 0s 880us/step - loss: 0.4333 - accuracy: 0.8074
Epoch 5/100
219/219 [==============================] - 0s 980us/step - loss: 0.4295 - accuracy: 0.8088
Epoch 6/100
219/219 [==============================] - 0s 876us/step - loss: 0.4187 - accuracy: 0.8170
Epoch 7/100
219/219 [==============================] - 0s 877us/step - loss: 0.4163 - accuracy: 0.8131
Epoch 8/100
219/219 [==============================] - 0s 847us/step - loss: 0.3986 - accuracy: 0.8235
Epoch 9/100
219/219 [==============================] - 0s 878us/step - loss: 0.3861 - accuracy: 0.8317
Epoch 10/100
219/219 [==============================] - 0s 862us/step - l

219/219 [==============================] - 0s 690us/step - loss: 0.3263 - accuracy: 0.8685
Epoch 80/100
219/219 [==============================] - 0s 649us/step - loss: 0.3302 - accuracy: 0.8695
Epoch 81/100
219/219 [==============================] - 0s 681us/step - loss: 0.3393 - accuracy: 0.8596
Epoch 82/100
219/219 [==============================] - 0s 649us/step - loss: 0.3454 - accuracy: 0.8612
Epoch 83/100
219/219 [==============================] - 0s 654us/step - loss: 0.3521 - accuracy: 0.8563
Epoch 84/100
219/219 [==============================] - 0s 672us/step - loss: 0.3358 - accuracy: 0.8610
Epoch 85/100
219/219 [==============================] - 0s 677us/step - loss: 0.3319 - accuracy: 0.8622
Epoch 86/100
219/219 [==============================] - 0s 654us/step - loss: 0.3325 - accuracy: 0.8636
Epoch 87/100
219/219 [==============================] - 0s 672us/step - loss: 0.3490 - accuracy: 0.8563
Epoch 88/100
219/219 [==============================] - 0s 824us/step - loss:

### Predicting the result

In [34]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the confusion Matrix

In [44]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(" Confusion matrix:\n {}".format(confusion_matrix(y_test,y_pred)))
print(" Accuracy rate: {:.2f} %".format(accuracy_score(y_test,y_pred)*100))

 Confusion matrix:
 [[2313  103]
 [ 316  268]]
 Accuracy rate: 86.03 %


### Predicting the result with the following information


Use our ANN model to predict if the customer with the following informations will leave the bank:
Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer ?

In [53]:
predict=ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))
if(predict>=.50):
    print("Yes,Customer will stay with the bank")
else:
    print("No, Customer will live the Bank vey soon, act accordingly ")

No, Customer will live the Bank vey soon, act accordingly 
